/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CircuitsIndexRouteImport } from './routes/circuits.index'
import { Route as CircuitsSlugRouteImport } from './routes/circuits.$slug'
import { Route as MotosIndexRouteImport } from './routes/motos.index'
import { Route as MotosSlugRouteImport } from './routes/motos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsIndexRoute = CircuitsIndexRouteImport.update({
  id: '/circuits/',
  path: '/circuits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsSlugRoute = CircuitsSlugRouteImport.update({
  id: '/circuits/$slug',
  path: '/circuits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MotosIndexRoute = MotosIndexRouteImport.update({
  id: '/motos/',
  path: '/motos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotosSlugRoute = MotosSlugRouteImport.update({
  id: '/motos/$slug',
  path: '/motos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/carte': typeof CarteRoute
  '/cgv': typeof CgvRoute
  '/compte': typeof CompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/reservation': typeof ReservationRoute
  '/api/chat': typeof ApiChatRoute
  '/circuits/$slug': typeof CircuitsSlugRoute
  '/motos/$slug': typeof MotosSlugRoute
  '/circuits/': typeof CircuitsIndexRoute
  '/motos/': typeof MotosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/carte': typeof CarteRoute
  '/cgv': typeof CgvRoute
  '/compte': typeof CompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/reservation': typeof ReservationRoute
  '/api/chat': typeof ApiChatRoute
  '/circuits/$slug': typeof CircuitsSlugRoute
  '/motos/$slug': typeof MotosSlugRoute
  '/circuits': typeof CircuitsIndexRoute
  '/motos': typeof MotosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/carte': typeof CarteRoute
  '/cgv': typeof CgvRoute
  '/compte': typeof CompteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/reservation': typeof ReservationRoute
  '/api/chat': typeof ApiChatRoute
  '/circuits/$slug': typeof CircuitsSlugRoute
  '/motos/$slug': typeof MotosSlugRoute
  '/circuits/': typeof CircuitsIndexRoute
  '/motos/': typeof MotosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/activites'
    | '/carte'
    | '/cgv'
    | '/compte'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/mentions-legales'
    | '/reservation'
    | '/api/chat'
    | '/circuits/$slug'
    | '/motos/$slug'
    | '/circuits/'
    | '/motos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/activites'
    | '/carte'
    | '/cgv'
    | '/compte'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/mentions-legales'
    | '/reservation'
    | '/api/chat'
    | '/circuits/$slug'
    | '/motos/$slug'
    | '/circuits'
    | '/motos'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/activites'
    | '/carte'
    | '/cgv'
    | '/compte'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/mentions-legales'
    | '/reservation'
    | '/api/chat'
    | '/circuits/$slug'
    | '/motos/$slug'
    | '/circuits/'
    | '/motos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActivitesRoute: typeof ActivitesRoute
  CarteRoute: typeof CarteRoute
  CgvRoute: typeof CgvRoute
  CompteRoute: typeof CompteRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ReservationRoute: typeof ReservationRoute
  ApiChatRoute: typeof ApiChatRoute
  CircuitsSlugRoute: typeof CircuitsSlugRoute
  MotosSlugRoute: typeof MotosSlugRoute
  CircuitsIndexRoute: typeof CircuitsIndexRoute
  MotosIndexRoute: typeof MotosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits/': {
      id: '/circuits/'
      path: '/circuits'
      fullPath: '/circuits/'
      preLoaderRoute: typeof CircuitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits/$slug': {
      id: '/circuits/$slug'
      path: '/circuits/$slug'
      fullPath: '/circuits/$slug'
      preLoaderRoute: typeof CircuitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motos/': {
      id: '/motos/'
      path: '/motos'
      fullPath: '/motos/'
      preLoaderRoute: typeof MotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motos/$slug': {
      id: '/motos/$slug'
      path: '/motos/$slug'
      fullPath: '/motos/$slug'
      preLoaderRoute: typeof MotosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActivitesRoute: ActivitesRoute,
  CarteRoute: CarteRoute,
  CgvRoute: CgvRoute,
  CompteRoute: CompteRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ReservationRoute: ReservationRoute,
  ApiChatRoute: ApiChatRoute,
  CircuitsSlugRoute: CircuitsSlugRoute,
  MotosSlugRoute: MotosSlugRoute,
  CircuitsIndexRoute: CircuitsIndexRoute,
  MotosIndexRoute: MotosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
